### ISSUE TITLE
This example video URL is giving me a very, very bad experience🧑

### ISSUE THREAD

**Issue by CCMeta** [samuraime/bldl#1]
https://www.bilibili.com/video/BV1ac411E7jr

This example video URL is giving me a very, very bad experience
Looking to replace the BV1ac411E7jr to a 'tall' 'big' 'upper' video
such as the history of philosophy or the history of art

**Comment by samuraime** [comment]
Sorry for giving you this kind of feeling.
Still need a small size video which probably be low quality and short enough video, updated with https://www.bilibili.com/video/BV1j4411W7F7, most popular video in Bilibili, no `one of`.

**Comment by CCMeta** [comment]
that feel better! Thanks a lot.
